config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :products do
    collection do
      get 'search'
    end
  end
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/contact', to: 'static_pages#contact_us'
  get '/product/:country', to: 'products#showbycountry'
  get '/about', to: 'static_pages#about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  before_save { self.product_name = product_name.titlecase }

  belongs_to :user

  def self.search(params)
    products = Product.where(country:params)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show, :showbycountry]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @user = User.all
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @products = Product.search(params)
  end

  def showbycountry
    @products_country = Product.where(country: params[:country])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      if params[:country]
        @products_country = Product.where(:country, params[:country])
      else
        @product = Product.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_name, :country, :product_description, :price)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @products = Product.all
  end

  def help
  end

  def contact_us
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @products = @user.products
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top">
    <div class="container">
      <!-- <%= link_to "Tompang", '/', id: "logo" %> -->
      <a class="navbar-brand" id="logo" href="/">
      <%= image_tag("logo.png", size: "40x30", :alt => "Tompang the World") %>
      </a>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "About",   '/about' %></li>
          <li><%=link_to 'Sell', new_product_path %></li>
          <li><%= link_to 'Buy', products_path %></li>
          <li><%= link_to "Contact Us",   '/contact' %></li>
          <li><%= link_to "Help",   '/help' %></li>

          <% if user_signed_in? %>
            <li><%=link_to 'Account', edit_user_registration_path %></li>
            <li><%=link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> Tompang the World</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |name,msg| %>
      <%= content_tag(:div, msg, class:"alert alert-#{name}") %>
      <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= simple_form_for @product do |f| %>


      <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>


      <%= f.input :product_name, placeholder: "What are you selling?", required: 'true'  %>
      <%= f.input :country, include_blank: false, priority: [ "Singapore" ], required: 'true'  %>
      <%= f.input :product_description, placeholder: "What's cool about it?", required: 'true'  %>
      <%= f.input :price, placeholder: "How much is it?", required: 'true' %>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<% provide(:title, "Products") %>

<p id="notice"><%= notice %></p>
<h1>Products</h1>

<div class="form-group col-sm-12">
  <label for="country"><h3>Choose Country:</h3></label>
  <select       class = "form-control"
                   id = "country"
             onchange = "window.location.href = '/product/' + this.value;">
    <% @products.each do |product| %>
    <option><%= link_to "#{product.country}", "/product/#{product.country}" %></option>
    <% end %>
  </select>
</div>

<% @products.each do |product| %>
<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="card">
    <div class="card-img thumbnail img-responsive" style="background-image: url(<%= product[:imgurl]%>)"></div>
    <!-- <img class="card-img img-responsive" src="<%= product[:imgurl]%>" alt="Card image cap"> -->
    <div class="card-block">
      <h4 class="card-title"><%= link_to product.product_name, product %></h4>
      <p class="card-text" id="country"><%= product.country %>
      <p class="card-text"><%=
      truncate( product.product_description, length: 90, omission: '...') %>
    </div>
  </div>
</div>
<% end %>

app/views/products/new.html.erb
<% provide(:title, "Products") %>
<h1>New Product</h1>

<%= render 'form', product: @product %>

app/views/products/search.html.erb
<% @products.each do |product| %>
  <%= product.name %>
<% end %>

app/views/products/show.html.erb
<% provide(:title, "Products") %>
<p id="notice"><%= notice %></p>

<div class="container col-lg-6">
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%=link_to @product.product_name, products_path(@product)%>
    </h3>
    <p class="panel-title">Listed by:<em> <%= link_to @product.user.first_name, user_url %> </em></p>
  </div>
  <div class="panel-body">
    <p>
      <strong>Product Description:</strong><br>
      <%= @product.product_description %>
    </p>

    <p>
      <strong>Price:</strong><br>
      $<%= number_with_precision(@product.price, precision:2) %>
    </p>

    <% if @product.user == current_user %>
      <div class="btn-group">
      <%= link_to 'Edit', edit_product_path, type:"button", class:"btn btn-default"%>
      <%= link_to 'Remove', @product, method: :delete, data: { confirm: 'Are you sure?' }, type:"button", class:"btn btn-default" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/products/showbycountry.html.erb
<% @products_country.each do |product| %>
<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="card">
    <!-- <img class="card-img img-responsive" src="..." alt="Card image cap"> -->
    <div class="card-img thumbnail img-responsive" style="background-image: url(<%= product[:imgurl]%>)"></div>
    <div class="card-block">
      <h4 class="card-title"><%= product.product_name %></h4>
      <p class="card-text" id="country"><%= product.country %></p>
      <p class="card-text"><%= link_to product.product_description, product %></p>
    </div>
  </div>
</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About |") %>

<div class = "center jumbotron">

  <h1>About</h1>
  <%= image_tag("logo.png", :alt => "Tompang the World") %>

  <p>
  Actually selfies you probably haven't heard of them dreamcatcher fashion axe. Umami man braid quinoa forage squid knausgaard affogato normcore. Artisan schlitz hoodie, YOLO pork belly iPhone fap next level swag venmo hella sartorial narwhal single-origin coffee. Hashtag flannel pork belly fanny pack, brooklyn ramps vice church-key umami locavore waistcoat. Drinking vinegar small batch helvetica polaroid fap. Kickstarter tofu farm-to-table, helvetica microdosing gastropub street art offal meh. Tacos chicharrones health goth, craft beer messenger bag slow-carb 8-bit crucifix godard authentic cornhole.
  </p>
</div>

app/views/static_pages/contact_me.html.erb
<h1>StaticPages#contact_me</h1>
<p>Find me in app/views/static_pages/contact_me.html.erb</p>

app/views/static_pages/contact_us.html.erb
<% provide(:title, "Contact Us |") %>

<div class="jumbotron">
  <h1>Contact Us</h1>
  <p>Find me in app/views/static_pages/contact_me.html.erb</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help |") %>

<div class="jumbotron">
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home |") %>

<div class="block">
  <h1>Tompang<br> the World</h1>

  <div class="form-group col-sm-12">
    <label for="country"><h3>Tompang from these Countries:</h3></label>
    <select class="form-control" id="country" onchange="window.location.href = '/product/' + this.value;">
      <% @products.each do |product| %>
      <option><%= link_to "#{product.country}", "/product/#{product.country}"  %></option>
      <% end %>
    </select>
  </div>

  <%= video_tag("home.mp4", autoplay: true, loop: true, muted: true, controls: false) %>

</div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

<h1><%= @user.first_name %><%= @user.last_name %></h1>

<% @products.each do |product| %>
<div class="col-sm-6 col-md-4 col-lg-3">
  <div class="card">
    <img class="card-img img-responsive" src="..." alt="Card image cap">
    <div class="card-block">
      <h4 class="card-title"><%= link_to product.product_name, product %></h4>
      <p class="card-text" id="country"><%= product.country %>
      <p class="card-text"><%=
      truncate( product.product_description, length: 90, omission: '...') %>
    </div>
  </div>
</div>
<% end %>

  <% if @user == current_user %>
    <div class="btn-group">
    <%= link_to 'Edit', edit_product_path(product), type:"button", class:"btn btn-default"%>
    <%= link_to 'Remove', product, method: :delete, data: { confirm: 'Are you sure?' }, type:"button", class:"btn btn-default" %>
    </div>
  <% end %>
</div>